version: '3.5'
 
services:
            
  service-php:
    image: ${USERHUB}/${ARTIFACT}:${NUMBER}
    ports:
      - 6004:80
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
